name: Changesets

on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

concurrency: ${{ github.workflow }}-{{ github.ref}}

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [16.x, 18.x]
    #     fail-fast: true

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2
        with:
          version: 7
      # - name: Use Node.js ${{matrix.node-version}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm
      - name: Installing dependencies
        run: pnpm install
      - name: Create realease PR and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          # version: pnpm ci:version
          # commit: "chore: update versions"
          # title: "chore: update versions"
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}